# ---------------------------------------------------------------------------
# Run in CMake script mode (-P). Turns the static SvelteKit build output into a
# single C++ translation unit holding every asset as a byte array.
#
#   ASSET_DIR      directory containing the SvelteKit `build/` output
#   OUTPUT_FILE    .cpp file to generate
#   EMBED_ENABLED  ON  -> walk ASSET_DIR and embed everything found
#                  OFF -> emit an empty table so the backend still links
#
# Phase 5 note: C++23 `#embed` would replace the hex-array generation below
# once the toolchain floor moves; the table shape stays the same either way.
# ---------------------------------------------------------------------------

function(mime_for_extension ext out_var)
    string(TOLOWER "${ext}" ext)
    set(mime "application/octet-stream")
    if(ext STREQUAL ".html" OR ext STREQUAL ".htm")
        set(mime "text/html; charset=utf-8")
    elseif(ext STREQUAL ".js" OR ext STREQUAL ".mjs")
        set(mime "text/javascript; charset=utf-8")
    elseif(ext STREQUAL ".css")
        set(mime "text/css; charset=utf-8")
    elseif(ext STREQUAL ".json" OR ext STREQUAL ".map")
        set(mime "application/json; charset=utf-8")
    elseif(ext STREQUAL ".svg")
        set(mime "image/svg+xml")
    elseif(ext STREQUAL ".png")
        set(mime "image/png")
    elseif(ext STREQUAL ".jpg" OR ext STREQUAL ".jpeg")
        set(mime "image/jpeg")
    elseif(ext STREQUAL ".webp")
        set(mime "image/webp")
    elseif(ext STREQUAL ".ico")
        set(mime "image/x-icon")
    elseif(ext STREQUAL ".woff2")
        set(mime "font/woff2")
    elseif(ext STREQUAL ".woff")
        set(mime "font/woff")
    elseif(ext STREQUAL ".txt")
        set(mime "text/plain; charset=utf-8")
    elseif(ext STREQUAL ".wasm")
        set(mime "application/wasm")
    endif()
    set(${out_var} "${mime}" PARENT_SCOPE)
endfunction()

# Whether an asset is worth pre-compressing. Fonts, images and wasm are already
# compressed; running deflate over them again spends binary size to make the
# payload very slightly larger.
function(is_compressible mime out_var)
    set(answer OFF)
    if(mime MATCHES "^text/" OR mime MATCHES "^application/json" OR mime MATCHES "image/svg")
        set(answer ON)
    endif()
    set(${out_var} "${answer}" PARENT_SCOPE)
endfunction()

# Compresses `input` with `tool` into `output` and returns its hex, but only if
# the result is meaningfully smaller. A variant that saves a handful of bytes
# costs more in binary size than it ever saves on the wire, and one that is
# *larger* would be served in place of the original.
# `to_stdout` distinguishes the two tools' calling conventions: gzip writes the
# compressed stream to standard output, brotli takes an -o destination.
function(compress_variant tool args to_stdout input output out_hex out_bytes)
    set(${out_hex} "" PARENT_SCOPE)
    set(${out_bytes} 0 PARENT_SCOPE)
    if(NOT tool)
        return()
    endif()

    file(REMOVE "${output}")
    if(to_stdout)
        execute_process(COMMAND ${tool} ${args} RESULT_VARIABLE status
                        OUTPUT_FILE "${output}" ERROR_QUIET)
    else()
        execute_process(COMMAND ${tool} ${args} RESULT_VARIABLE status
                        OUTPUT_QUIET ERROR_QUIET)
    endif()
    if(NOT status EQUAL 0 OR NOT EXISTS "${output}")
        return()
    endif()

    file(SIZE "${input}" raw_size)
    file(SIZE "${output}" packed_size)
    math(EXPR threshold "${raw_size} * 9 / 10")
    if(packed_size GREATER_EQUAL threshold)
        file(REMOVE "${output}")
        return()
    endif()

    file(READ "${output}" hex HEX)
    file(REMOVE "${output}")
    string(REGEX REPLACE "(..)" "0x\\1," hex "${hex}")
    string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)"
                         "\\1\n    " hex "${hex}")
    set(${out_hex} "${hex}" PARENT_SCOPE)
    set(${out_bytes} "${packed_size}" PARENT_SCOPE)
endfunction()

set(HEADER "// Generated by EmbedFrontend.cmake — do not edit.\n#include \"server/asset_store.hpp\"\n\nnamespace monobucket::assets {\n")
set(BODY "")
set(ENTRIES "")
set(COUNT 0)
set(TOTAL_BYTES 0)
set(PACKED_BYTES 0)

# Both optional. Neither is a build dependency: without them the table simply
# carries no variants and every response is served as-is, which is what the
# server does for an incompressible asset anyway.
find_program(GZIP_TOOL gzip)
find_program(BROTLI_TOOL brotli)

if(EMBED_ENABLED AND IS_DIRECTORY "${ASSET_DIR}")
    file(GLOB_RECURSE ASSET_FILES RELATIVE "${ASSET_DIR}" "${ASSET_DIR}/*")
    list(SORT ASSET_FILES)

    foreach(rel IN LISTS ASSET_FILES)
        set(abs "${ASSET_DIR}/${rel}")
        if(IS_DIRECTORY "${abs}")
            continue()
        endif()

        file(READ "${abs}" hex HEX)
        string(LENGTH "${hex}" hexlen)
        math(EXPR bytes "${hexlen} / 2")
        math(EXPR TOTAL_BYTES "${TOTAL_BYTES} + ${bytes}")

        # 0a1b2c -> 0x0a,0x1b,0x2c with a newline every 32 bytes.
        string(REGEX REPLACE "(..)" "0x\\1," hex "${hex}")
        string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)"
                             "\\1\n    " hex "${hex}")

        # LAST_EXT, not EXT: Vite fingerprints assets as `app.EZ5uSd-D.js`, and
        # EXT would return `.EZ5uSd-D.js`. Getting this wrong serves modules as
        # application/octet-stream, which browsers refuse to execute.
        get_filename_component(ext "${rel}" LAST_EXT)
        mime_for_extension("${ext}" mime)

        set(gzip_hex "")
        set(gzip_bytes 0)
        set(brotli_hex "")
        set(brotli_bytes 0)
        is_compressible("${mime}" compressible)
        if(compressible)
            set(tmp "${OUTPUT_FILE}.variant")
            compress_variant("${GZIP_TOOL}" "-9;-c;${abs}" ON "${abs}" "${tmp}"
                             gzip_hex gzip_bytes)
            compress_variant("${BROTLI_TOOL}" "-q;11;-f;-o;${tmp};${abs}" OFF "${abs}" "${tmp}"
                             brotli_hex brotli_bytes)
            math(EXPR PACKED_BYTES "${PACKED_BYTES} + ${gzip_bytes} + ${brotli_bytes}")
        endif()

        string(APPEND BODY "namespace {\nconstexpr unsigned char kAsset${COUNT}[] = {\n    ${hex}\n};\n")
        set(gzip_ref "nullptr")
        set(brotli_ref "nullptr")
        if(gzip_bytes GREATER 0)
            string(APPEND BODY "constexpr unsigned char kAsset${COUNT}Gz[] = {\n    ${gzip_hex}\n};\n")
            set(gzip_ref "kAsset${COUNT}Gz")
        endif()
        if(brotli_bytes GREATER 0)
            string(APPEND BODY "constexpr unsigned char kAsset${COUNT}Br[] = {\n    ${brotli_hex}\n};\n")
            set(brotli_ref "kAsset${COUNT}Br")
        endif()
        string(APPEND BODY "}  // namespace\n\n")

        string(APPEND ENTRIES "    Asset{\"/${rel}\", \"${mime}\", kAsset${COUNT}, ${bytes}, ${gzip_ref}, ${gzip_bytes}, ${brotli_ref}, ${brotli_bytes}},\n")
        math(EXPR COUNT "${COUNT} + 1")
    endforeach()
endif()

if(COUNT EQUAL 0)
    set(TABLE "const Asset* tableData() noexcept { return nullptr; }\nstd::size_t tableSize() noexcept { return 0; }\n")
else()
    set(TABLE "namespace {\nconstexpr Asset kTable[] = {\n${ENTRIES}};\n}  // namespace\n\nconst Asset* tableData() noexcept { return kTable; }\nstd::size_t tableSize() noexcept { return ${COUNT}; }\n")
endif()

file(WRITE "${OUTPUT_FILE}" "${HEADER}${BODY}${TABLE}\n}  // namespace monobucket::assets\n")

set(PACKED_NOTE "")
if(COUNT GREATER 0)
    set(TOOLS "")
    if(GZIP_TOOL)
        string(APPEND TOOLS " gzip")
    endif()
    if(BROTLI_TOOL)
        string(APPEND TOOLS " brotli")
    endif()
    if(TOOLS STREQUAL "")
        set(PACKED_NOTE ", no compressor found — assets served uncompressed")
    else()
        set(PACKED_NOTE ", +${PACKED_BYTES} byte(s) of pre-compressed variants (${TOOLS})")
    endif()
endif()

message(STATUS "EmbedFrontend: ${COUNT} asset(s), ${TOTAL_BYTES} byte(s)${PACKED_NOTE} -> ${OUTPUT_FILE}")
