# ---------------------------------------------------------------------------
# Run in CMake script mode (-P). Turns the static SvelteKit build output into a
# single C++ translation unit holding every asset as a byte array.
#
#   ASSET_DIR      directory containing the SvelteKit `build/` output
#   OUTPUT_FILE    .cpp file to generate
#   EMBED_ENABLED  ON  -> walk ASSET_DIR and embed everything found
#                  OFF -> emit an empty table so the backend still links
#
# Phase 5 note: C++23 `#embed` would replace the hex-array generation below
# once the toolchain floor moves; the table shape stays the same either way.
# ---------------------------------------------------------------------------

function(mime_for_extension ext out_var)
    string(TOLOWER "${ext}" ext)
    set(mime "application/octet-stream")
    if(ext STREQUAL ".html" OR ext STREQUAL ".htm")
        set(mime "text/html; charset=utf-8")
    elseif(ext STREQUAL ".js" OR ext STREQUAL ".mjs")
        set(mime "text/javascript; charset=utf-8")
    elseif(ext STREQUAL ".css")
        set(mime "text/css; charset=utf-8")
    elseif(ext STREQUAL ".json" OR ext STREQUAL ".map")
        set(mime "application/json; charset=utf-8")
    elseif(ext STREQUAL ".svg")
        set(mime "image/svg+xml")
    elseif(ext STREQUAL ".png")
        set(mime "image/png")
    elseif(ext STREQUAL ".jpg" OR ext STREQUAL ".jpeg")
        set(mime "image/jpeg")
    elseif(ext STREQUAL ".webp")
        set(mime "image/webp")
    elseif(ext STREQUAL ".ico")
        set(mime "image/x-icon")
    elseif(ext STREQUAL ".woff2")
        set(mime "font/woff2")
    elseif(ext STREQUAL ".woff")
        set(mime "font/woff")
    elseif(ext STREQUAL ".txt")
        set(mime "text/plain; charset=utf-8")
    elseif(ext STREQUAL ".wasm")
        set(mime "application/wasm")
    endif()
    set(${out_var} "${mime}" PARENT_SCOPE)
endfunction()

set(HEADER "// Generated by EmbedFrontend.cmake — do not edit.\n#include \"server/asset_store.hpp\"\n\nnamespace monobucket::assets {\n")
set(BODY "")
set(ENTRIES "")
set(COUNT 0)
set(TOTAL_BYTES 0)

if(EMBED_ENABLED AND IS_DIRECTORY "${ASSET_DIR}")
    file(GLOB_RECURSE ASSET_FILES RELATIVE "${ASSET_DIR}" "${ASSET_DIR}/*")
    list(SORT ASSET_FILES)

    foreach(rel IN LISTS ASSET_FILES)
        set(abs "${ASSET_DIR}/${rel}")
        if(IS_DIRECTORY "${abs}")
            continue()
        endif()

        file(READ "${abs}" hex HEX)
        string(LENGTH "${hex}" hexlen)
        math(EXPR bytes "${hexlen} / 2")
        math(EXPR TOTAL_BYTES "${TOTAL_BYTES} + ${bytes}")

        # 0a1b2c -> 0x0a,0x1b,0x2c with a newline every 32 bytes.
        string(REGEX REPLACE "(..)" "0x\\1," hex "${hex}")
        string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)"
                             "\\1\n    " hex "${hex}")

        # LAST_EXT, not EXT: Vite fingerprints assets as `app.EZ5uSd-D.js`, and
        # EXT would return `.EZ5uSd-D.js`. Getting this wrong serves modules as
        # application/octet-stream, which browsers refuse to execute.
        get_filename_component(ext "${rel}" LAST_EXT)
        mime_for_extension("${ext}" mime)

        string(APPEND BODY "namespace {\nconstexpr unsigned char kAsset${COUNT}[] = {\n    ${hex}\n};\n}  // namespace\n\n")
        string(APPEND ENTRIES "    Asset{\"/${rel}\", \"${mime}\", kAsset${COUNT}, ${bytes}},\n")
        math(EXPR COUNT "${COUNT} + 1")
    endforeach()
endif()

if(COUNT EQUAL 0)
    set(TABLE "const Asset* tableData() noexcept { return nullptr; }\nstd::size_t tableSize() noexcept { return 0; }\n")
else()
    set(TABLE "namespace {\nconstexpr Asset kTable[] = {\n${ENTRIES}};\n}  // namespace\n\nconst Asset* tableData() noexcept { return kTable; }\nstd::size_t tableSize() noexcept { return ${COUNT}; }\n")
endif()

file(WRITE "${OUTPUT_FILE}" "${HEADER}${BODY}${TABLE}\n}  // namespace monobucket::assets\n")

message(STATUS "EmbedFrontend: ${COUNT} asset(s), ${TOTAL_BYTES} byte(s) -> ${OUTPUT_FILE}")
